# Generated by Django 5.2 on 2025-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('customer', 'Customer')], max_length=11),
        ),
    ]
