# Generated by Django 5.2 on 2025-05-04 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0004_remove_review_dish_remove_review_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dop_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default='г. Астана, ул. Примерная, 123', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Готовится'), ('Completed', 'Доставляется'), ('', 'Доставлен')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ManyToManyField(blank=True, default='', related_name='customer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
